import numpy as np
USE_RANDOM_GRID = False
CROP_CODE = 5 # Not to be used
GRID_SIZE = 100
GRID_RES = 50
NUM_DRONES = 3
NUM_CUSTOMERS = 10
COALITION_PERCENT = 0.9
DRONE_SPEED = 1  
BASE_LOC = (GRID_RES/2, GRID_RES/2)