import numpy as np
USE_RANDOM_GRID = True
GRID_SIZE = 40
GRID_RES = 20
NUM_DRONES = 3
NUM_CUSTOMERS = 6
COALITION_PERCENT = 0.3
DRONE_SPEED = 0.5
CROP_CODE = 5
BASE_LOC = np.array([GRID_SIZE / 2, GRID_SIZE / 2])